[theme]
base = "light"
primaryColor = "#CC092F"           # vermelho Bradesco
backgroundColor = "#FFFFFF"        # branco
secondaryBackgroundColor = "#F5F5F5"  # cinza claro
textColor = "#313131"              # quase-preto Bradesco
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
